CREATE TABLE categories (id BIGSERIAL PRIMARY KEY,name VARCHAR(150) NOT NULL UNIQUE,description VARCHAR(500),created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE products (id BIGSERIAL PRIMARY KEY,sku VARCHAR(100) NOT NULL UNIQUE,name VARCHAR(255) NOT NULL,description TEXT,price NUMERIC(18,2) NOT NULL DEFAULT 0,category_id BIGINT,status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX idx_products_category ON products(category_id);
