rootProject.name = 'JavaLogictics'

include 'services:api-gateway'
include 'services:auth-service'
include 'services:product-service'
include 'services:warehouse-service'
include 'services:inventory-service'
include 'services:order-service'
include 'services:shipment-service'
include 'services:notification-service'