CREATE TABLE warehouses (id BIGSERIAL PRIMARY KEY,code VARCHAR(50) NOT NULL UNIQUE,name VARCHAR(255) NOT NULL,location VARCHAR(255),address VARCHAR(500),created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE warehouse_zones (id BIGSERIAL PRIMARY KEY,warehouse_id BIGINT NOT NULL,code VARCHAR(50) NOT NULL,name VARCHAR(150) NOT NULL,UNIQUE(warehouse_id,code));
